import discord
from discord.ext import commands
import colorama
from colorama import Fore
import asyncio
from webserver import keep_alive
import os

prefix = "/"

keep_alive()
token = os.getenv("token")



bot = commands.Bot(command_prefix=prefix,
                   help_command=None,
                   case_insensitive=True,
                   self_bot=True)



@bot.command()
async def helpdank(ctx):
    await ctx.message.delete()
    await ctx.send('**/start: SEX MC ON TOP W .gg/DCMYuGksE7, SEX MC ON TOP W .gg/DCMYuGksE7, SEX MC ON TOP W .gg/DCMYuGksE7, SEX MC ON TOP W .gg/DCMYuGksE7, : /stop: it's just there it doesn't stop the bot but hey it's here yk**')

@bot.command()
async def stop(ctx):
    await ctx.message.delete()
    await ctx.send('**SexMC Raid off**')
    global dmcs
    dmcs = False


@bot.command(pass_context=True)
async def start(ctx):
    await ctx.message.delete()
    await ctx.send('**SexMC Raid On**')
    global dmcs
    dmcs = True
    while dmcs: 
        async with ctx.typing():
            await asyncio.sleep(5)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            print(f"{Fore.GREEN}Break for 30 mins")
            await asyncio.sleep(1800)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            print(f"{Fore.GREEN}Break for 30 mins")
            await asyncio.sleep(1800)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")
            await asyncio.sleep(0)
            await ctx.send('SEX MC ON TOP W .gg/DCMYuGksE7')
            print(f"{Fore.GREEN}SEX MC ON TOP W .gg/DCMYuGksE7")

keep_alive()
bot.run(os.getenv('token'), bot=False)

